version: '3.7'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://user:password@db/mydatabase?charset=utf8mb4"
      BFLA_FLAG1: "flag{dummy_bfla_flag1}"
      BFLA_FLAG2: "flag{dummy_bfla_flag2}"
      BOLA_FLAG1: "flag{dummy_bola_flag1}"
      BOLA_FLAG2: "flag{dummy_bola_flag2}"
      SSRF_FLAG1: "flag{dummy_ssrf_flag1}"
      SSRF_FLAG2: "flag{dummy_ssrf_flag2}"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - api

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:
